
package COMIDA_RED;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author SDiego
 */
public class adminFrame2 extends javax.swing.JFrame {
    public static Registro registroadmin2;
    public static Menus menuadmin2;
    public static JComboBox<String> comboboxadmin2c;
    public static JComboBox<String> comboboxadmin2b;
    public String bebidaNueva;
    public double precioNuevo;
    public int posicion;
    /**
     * Creates new form adminFrame2
     */
    public adminFrame2() {
        initComponents();
      
        
        registroadmin2 = new Registro();
        menuadmin2 = adminFrame.menuadmin;
        comboboxadmin2c = new JComboBox();
        comboboxadmin2b = new JComboBox();
        bebidaNueva="";
        precioNuevo=0;
        posicion=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboxcomida1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        bnewcomida = new javax.swing.JButton();
        tpreciocomida = new javax.swing.JTextField();
        cboxbebida1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tpreciobebida = new javax.swing.JTextField();
        bnewbebida = new javax.swing.JButton();
        botonordenes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOrdenABorrar = new javax.swing.JTextField();
        jComboBoxBuscarOrden = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta de AdministradorRED - Restaurante RED, Pedidos Digitales");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Agregue una comida o bebida"));

        cboxcomida1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dona de chocolate", "Hut Dog", "Pollo empanizado", "Dobladas con carne", "Alitas con salsa barbacoa" }));
        cboxcomida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxcomida1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio de la comida:");

        bnewcomida.setText("Agregar comida");
        bnewcomida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewcomidaActionPerformed(evt);
            }
        });

        cboxbebida1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sprite", "Fanta", "Jugo de naranja", "Jugo de tamarindo", " " }));
        cboxbebida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxbebida1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio de la bebida:");

        bnewbebida.setText("Agregar bebida");
        bnewbebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewbebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpreciobebida, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bnewbebida)
                    .addComponent(cboxbebida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpreciocomida, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboxcomida1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnewcomida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxcomida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxbebida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpreciocomida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(tpreciobebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnewcomida)
                    .addComponent(bnewbebida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonordenes.setText("Revisar Ordenes Pendientes");
        botonordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonordenesActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Borrar ordenes"));

        jLabel2.setText("Escriba el Numero de carnet");

        jButton3.setText("Entregar Orden");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("** Para más informacion presione el botón: \"Revisar Ordenes\".");

        jTextFieldOrdenABorrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldOrdenABorrarFocusGained(evt);
            }
        });

        jComboBoxBuscarOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxBuscarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBuscarOrdenActionPerformed(evt);
            }
        });

        jLabel5.setText("Seleccione la orden");

        jButton1.setText("Buscar Ordenes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOrdenABorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxBuscarOrden, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldOrdenABorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botonregresar.setText("Regresar");
        botonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonregresar)
                        .addGap(182, 182, 182)
                        .addComponent(botonordenes, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonordenes)
                    .addComponent(botonregresar))
                .addGap(10, 10, 10))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Entrega de Ordenes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresarActionPerformed
        // TODO add your handling code here:
        adminFrame admin = new adminFrame();
        admin.setVisible(true);
        this.setVisible(false);
        adminFrame.registroadmin = registroadmin2;
        adminFrame.menuadmin = menuadmin2;
        adminFrame.comboboxadminc = comboboxadmin2c;
        adminFrame.comboboxadminb = comboboxadmin2b;
    }//GEN-LAST:event_botonregresarActionPerformed

    private void botonordenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonordenesActionPerformed
        // TODO add your handling code here:
        ordenesFrame ordenes = new ordenesFrame();
        ordenesFrame.jTextArea1.append("Las ordenes son: ");
        int i = -1;
        Ordenes orden =null;
        for(int e = 0; e<registroadmin2.getOrdenes().size();e++){
            orden = registroadmin2.getOrdenes().get(e);
            i = i+1;
            String comida = orden.getComida().getNombreComida();double precioc = orden.getComida().getPrecio();
            String bebida = orden.getBebida().getNombreBebida();double preciob = orden.getBebida().getPrecio();
            String user = orden.getUsuario().getNombre();String carnet = orden.getUsuario().getCarnet();
            String hora = orden.getHora(); String minuto = orden.getMinutos();
            double sumaprecios = precioc + preciob;
            ordenesFrame.jTextArea1.append(System.getProperty("line.separator"));
            ordenesFrame.jTextArea1.append(i+".Usuario: "+user+" Carnet: "+carnet+", pidio el menu: "+comida+" (Q."+precioc+") y "+bebida+" (Q."+preciob+"), con precio total de: Q."+sumaprecios+", para la siguiente hora: "+hora+":"+minuto);
        }
        ordenes.setVisible(true);
    }//GEN-LAST:event_botonordenesActionPerformed

    private void cboxbebida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxbebida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxbebida1ActionPerformed

    private void cboxcomida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxcomida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxcomida1ActionPerformed

    private void bnewbebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewbebidaActionPerformed
        // TODO add your handling code here:
        String precio = tpreciobebida.getText();
        if(precio.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double preciodb = Double.parseDouble(precio);
            String bebida = cboxbebida1.getSelectedItem().toString();
            menuadmin2.agregarBebidas(bebida, preciodb);
            comboboxadmin2b.addItem(bebida);
            menuadmin2.agregarBebidas(bebida, preciodb);
            tpreciobebida.setText("");
            JOptionPane.showMessageDialog(null, "Bebida agregada con exito");
        }
    }//GEN-LAST:event_bnewbebidaActionPerformed

    private void bnewcomidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewcomidaActionPerformed
        // TODO add your handling code here:
        String precio = tpreciocomida.getText();
        if(precio.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double preciodb = Double.parseDouble(precio);
            String comida = cboxcomida1.getSelectedItem().toString();
            menuadmin2.agregarComidas(comida, preciodb);            
            comboboxadmin2c.addItem(comida);
            tpreciocomida.setText("");
            JOptionPane.showMessageDialog(null, "Comida agregada");
        }
    }//GEN-LAST:event_bnewcomidaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ordenesFrame ordenes = new ordenesFrame();
        int i = -1;
        int oab;
        oab = 0;
        Ordenes orden = new Ordenes();
        try {
            oab=this.posicion;
            registroadmin2.borrarOrden(oab);
            JOptionPane.showMessageDialog(null, "Orden Entregada");
            jTextFieldOrdenABorrar.setText("");
            jComboBoxBuscarOrden.removeAllItems();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero de orden valido.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
           
            String aa;
            Registro s= new Registro();
            ArrayList<Ordenes> ss=null;
            aa=(jTextFieldOrdenABorrar.getText());
             // TODO add your handling code here:
            ordenesFrame ordenes = new ordenesFrame();
            int i = -1;
            Ordenes orden = new Ordenes();
            for(int e = 0; e<registroadmin2.getOrdenes().size();e++){
                orden = registroadmin2.getOrdenes().get(e);
                if (orden.getUsuario().getCarnet().equals(aa)) {
                    i = i+1;
                    String comida = orden.getComida().getNombreComida();
                    double precioc = orden.getComida().getPrecio();
                    String bebida = orden.getBebida().getNombreBebida();
                    double preciob = orden.getBebida().getPrecio();
                    String user = orden.getUsuario().getNombre();
                    String carnet = orden.getUsuario().getCarnet();
                    String hora = orden.getHora();
                    String minuto = orden.getMinutos();
                    double sumaprecios = precioc + preciob;
                    jComboBoxBuscarOrden.addItem( "Menu: "+comida+" y "+bebida+", con total de: Q."+sumaprecios);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un No. de Carnet valido");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldOrdenABorrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOrdenABorrarFocusGained
        // TODO add your handling code here:
        jComboBoxBuscarOrden.removeAllItems();
    }//GEN-LAST:event_jTextFieldOrdenABorrarFocusGained

    private void jComboBoxBuscarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBuscarOrdenActionPerformed
        // TODO add your handling code here:
        this.posicion=jComboBoxBuscarOrden.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxBuscarOrdenActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnewbebida;
    private javax.swing.JButton bnewcomida;
    private javax.swing.JButton botonordenes;
    private javax.swing.JButton botonregresar;
    private javax.swing.JComboBox<String> cboxbebida1;
    private javax.swing.JComboBox<String> cboxcomida1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox<String> jComboBoxBuscarOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldOrdenABorrar;
    private javax.swing.JTextField tpreciobebida;
    private javax.swing.JTextField tpreciocomida;
    // End of variables declaration//GEN-END:variables
}


