
package COMIDA_RED;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author SDiego
 */
public final class adminFrame2 extends javax.swing.JFrame {
    public static Registro registroadmin2;
    public static Menus menuadmin2;
    public String bebidaNueva;
    public double precioNuevo;
    public int posicion;
   
    /**
     * Creates new form adminFrame2
     */
    public adminFrame2() {
        initComponents();
        registroadmin2 = adminFrame.registroadmin;
        menuadmin2 = adminFrame.menuadmin;
        bebidaNueva="";
        precioNuevo=0;
        posicion=0;
        
        llenarComboBoxCarnetClientes();
    }
    
     public void llenarComboBoxCarnetClientes(){
        String[] list = registroadmin2.retornarListaUsuariosCarnet();
        cboxcarnetsclientes.addItem("");
        for(String item: list){
            cboxcarnetsclientes.addItem(item);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboxcomida = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        bnewcomida = new javax.swing.JButton();
        tpreciocomida = new javax.swing.JTextField();
        cboxbebida = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tpreciobebida = new javax.swing.JTextField();
        bnewbebida = new javax.swing.JButton();
        tpreciopostre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bnewpostre = new javax.swing.JButton();
        cboxpostre = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bbuscarordenes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboxcarnetsclientes = new javax.swing.JComboBox<>();
        jButtonEntregarOrdenCarnetIndividual = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxBuscarOrden = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bordenespendientes = new javax.swing.JButton();
        bentregarordenCola = new javax.swing.JButton();
        jButtonVerOrdenesHora = new javax.swing.JButton();
        botonregresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta de AdministradorRED - Restaurante RED, Pedidos Digitales");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Agregue una comida o bebida"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cboxcomida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboxcomida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hut Dog", "Pollo empanizado", "Dobladas con carne", "Alitas con salsa barbacoa" }));
        cboxcomida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxcomidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Precio de la comida:");

        bnewcomida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bnewcomida.setText("Agregar comida");
        bnewcomida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewcomidaActionPerformed(evt);
            }
        });

        tpreciocomida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cboxbebida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboxbebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sprite", "Fanta", "Jugo de naranja", "Jugo de tamarindo", " " }));
        cboxbebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxbebidaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Precio de la bebida:");

        tpreciobebida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        bnewbebida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bnewbebida.setText("Agregar bebida");
        bnewbebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewbebidaActionPerformed(evt);
            }
        });

        tpreciopostre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Precio del postre:");

        bnewpostre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bnewpostre.setText("Agregar Postre");
        bnewpostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewpostreActionPerformed(evt);
            }
        });

        cboxpostre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboxpostre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flan de chocolate", "Cubilete de chocolate" }));
        cboxpostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxpostreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpreciobebida, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bnewbebida)
                    .addComponent(cboxbebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpreciocomida, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bnewcomida, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboxcomida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bnewpostre)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboxpostre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tpreciopostre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxcomida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxbebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxpostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpreciocomida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(tpreciobebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpreciopostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnewcomida)
                    .addComponent(bnewbebida)
                    .addComponent(bnewpostre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("** Para más informacion presione el botón: \"Revisar Ordenes\".");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bbuscarordenes.setText("Buscar Ordenes");
        bbuscarordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarordenesActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoja un numero de carnet:");

        jButtonEntregarOrdenCarnetIndividual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEntregarOrdenCarnetIndividual.setText("Entregar Orden Usuario");
        jButtonEntregarOrdenCarnetIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntregarOrdenCarnetIndividualActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seleccione la orden");

        jComboBoxBuscarOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxBuscarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBuscarOrdenActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Consultar y Entregar Orden Con Carnet");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxBuscarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboxcarnetsclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(bbuscarordenes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jButtonEntregarOrdenCarnetIndividual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bbuscarordenes)
                    .addComponent(cboxcarnetsclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEntregarOrdenCarnetIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Consultas Generales");

        bordenespendientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bordenespendientes.setText("Revisar Ordenes Pendientes");
        bordenespendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordenespendientesActionPerformed(evt);
            }
        });

        bentregarordenCola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bentregarordenCola.setText("Entregar Orden en Cola");
        bentregarordenCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bentregarordenColaActionPerformed(evt);
            }
        });

        jButtonVerOrdenesHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVerOrdenesHora.setText("Ver Ordenes Hora");
        jButtonVerOrdenesHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerOrdenesHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bordenespendientes)
                .addGap(15, 15, 15)
                .addComponent(bentregarordenCola, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVerOrdenesHora, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bordenespendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(bentregarordenCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerOrdenesHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        botonregresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonregresar.setText("Regresar");
        botonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregresarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Manejo de Ordenes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Ordenes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresarActionPerformed
        // TODO add your handling code here:
        adminFrame admin = new adminFrame();
        admin.setVisible(true);
        this.setVisible(false);
        adminFrame.registroadmin = registroadmin2;
        adminFrame.menuadmin = menuadmin2;
        
    }//GEN-LAST:event_botonregresarActionPerformed

    private void bordenespendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordenespendientesActionPerformed
        // TODO add your handling code here:
        ordenesFrame ordenes = new ordenesFrame();
        ordenesFrame.jTextArea1.append("Las ordenes son: ");
        int i = -1;
        Ordenes orden =null;
        for(int e = 0; e<registroadmin2.getOrdenes().size();e++){
            orden = registroadmin2.getOrdenes().get(e);
            i = i+1;
            //String comida = orden.getComida().getNombreComida();double precioc = orden.getComida().getPrecio();
            //String bebida = orden.getBebida().getNombreBebida();double preciob = orden.getBebida().getPrecio();
            String user = orden.getUsuario().getNombre();String carnet = orden.getUsuario().getCarnet();
            String hora = orden.getHora(); String minuto = orden.getMinutos();
            //double sumaprecios = precioc + preciob;
            ordenesFrame.jTextArea1.append(System.getProperty("line.separator"));
            ordenesFrame.jTextArea1.append(i+".Usuario: "+user+" Carnet: "+carnet+", pidio el menu siguiente , para la siguiente hora: "+hora+":"+minuto+" :");
            Producto prod = new Producto();
            for(int k=0;k<orden.getPedido().size();k++){
                prod = orden.getPedido().get(k);
                ordenesFrame.jTextArea1.append(System.getProperty("line.separator"));
                ordenesFrame.jTextArea1.append(" - "+prod.getNombreProducto()+", con precio:"+prod.getPrecio());
            }
        }
        ordenes.setVisible(true);
    }//GEN-LAST:event_bordenespendientesActionPerformed

    private void cboxbebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxbebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxbebidaActionPerformed

    private void cboxcomidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxcomidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxcomidaActionPerformed

    private void bnewbebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewbebidaActionPerformed
        // TODO add your handling code here:
        
        
        try {
           String precio = tpreciobebida.getText();
        if(precio.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double preciodb = Double.parseDouble(precio);
            String bebida = cboxbebida.getSelectedItem().toString();
            menuadmin2.agregarProductos("Bebida",bebida,preciodb);
            tpreciobebida.setText("");
            JOptionPane.showMessageDialog(null, "Bebida agregada con exito");
        }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores de dinero en el campo de precio, no letras.");
        }
    }//GEN-LAST:event_bnewbebidaActionPerformed

    private void bnewcomidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewcomidaActionPerformed
        // TODO add your handling code here:
        
        try {
            String precio = tpreciocomida.getText();
        if(precio.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double preciodb = Double.parseDouble(precio);
            String comida = cboxcomida.getSelectedItem().toString();
            menuadmin2.agregarProductos("Comida",comida, preciodb);            
            tpreciocomida.setText("");
            JOptionPane.showMessageDialog(null, "Comida agregada");
        }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores de dinero en el campo de precio, no letras.");
        }
    }//GEN-LAST:event_bnewcomidaActionPerformed

    private void bentregarordenColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentregarordenColaActionPerformed
        // TODO add your handling code here:
        ordenesFrame ordenes = new ordenesFrame();
        int i = -1;
        int oab;
        oab = 0;
        Ordenes orden = new Ordenes();
        try {
            oab=this.posicion;
            registroadmin2.borrarOrden(oab);
            
            //jTextFieldOrdenABorrar.setText("");
            jComboBoxBuscarOrden.removeAllItems();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero de orden valido.");
        }
    }//GEN-LAST:event_bentregarordenColaActionPerformed

    private void bbuscarordenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarordenesActionPerformed
        // TODO add your handling code here:
        try {
            if(cboxcarnetsclientes.getSelectedItem().toString().length()==0){
                JOptionPane.showMessageDialog(null, "No hay un carnet seleccionado.\nPorfavor seleccione uno.");
            }else{
                llenarComboboxOrdenes();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un No. de Carnet valido");
        }
    }//GEN-LAST:event_bbuscarordenesActionPerformed

    private void jComboBoxBuscarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBuscarOrdenActionPerformed
        // TODO add your handling code here:
        
         try {
           this.posicion=jComboBoxBuscarOrden.getSelectedIndex();
            
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inténtelo de nuevo.");
        }
        
        
    }//GEN-LAST:event_jComboBoxBuscarOrdenActionPerformed
        
    public void llenarComboboxOrdenes(){
        String carnet;
            String ordenAentregar="Orden de: ";
            carnet=cboxcarnetsclientes.getSelectedItem().toString();
            jComboBoxBuscarOrden.removeAllItems();
            
            ordenesFrame ordenes = new ordenesFrame();
            int i = -1;
            Ordenes orden = new Ordenes();
            
            for(int e = 0; e<registroadmin2.getOrdenes().size();e++){
                orden = registroadmin2.getOrdenes().get(e);
                if (orden.getUsuario().getCarnet().equals(carnet)) {
                    i = i+1;
                    
                    //double sumaprecios = precioc + preciob;
                    //jComboBoxBuscarOrden.addItem( "Menu: "+comida+" y "+bebida+", con total de: Q."+sumaprecios);
                    Producto prod= new Producto();
                    for(int k=0;k<orden.getPedido().size();k++){
                        prod = orden.getPedido().get(k);
                        ordenAentregar= ordenAentregar +prod.getNombreProducto()+", ";
                        
                    }
                    jComboBoxBuscarOrden.addItem(ordenAentregar);
                  
                    
                }
                ordenAentregar="Orden de: ";
                
                    
                }
    }
    private void jButtonEntregarOrdenCarnetIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntregarOrdenCarnetIndividualActionPerformed
        // TODO add your handling code here:
        
        try {
            
            String carnet;
            carnet=cboxcarnetsclientes.getSelectedItem().toString();
            
            ordenesFrame ordenes = new ordenesFrame();
            int contador=0;
            Ordenes orden = new Ordenes();
            for(int e = 0; e<registroadmin2.getOrdenes().size();e++){
                orden = registroadmin2.getOrdenes().get(e);
                if (orden.getUsuario().getCarnet().equals(carnet)) {
                  contador++;
                }
            }
            
            String[] arrayID= new String[contador];
            int contadorArray=0;
            Ordenes orden2= new Ordenes();
             for (int i = 0; i < registroadmin2.getOrdenes().size(); i++) {
                 orden2=registroadmin2.getOrdenes().get(i);
                 if (orden2.getUsuario().getCarnet().equals(carnet)) {
                     arrayID[contadorArray]=orden2.getIdOrden();
                     contadorArray++;
                 }
             }
            //System.out.println("Vector id "+Arrays.asList(arrayID));
            String idBorrar=arrayID[this.posicion];
            registroadmin2.borrarOrdenId(idBorrar);
            llenarComboboxOrdenes();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay una orden seleccionada para entregar.");
        }        
    }//GEN-LAST:event_jButtonEntregarOrdenCarnetIndividualActionPerformed

    private void bnewpostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewpostreActionPerformed
        // TODO add your handling code here:
        try {
            String precio = tpreciopostre.getText();
        if(precio.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double preciodb = Double.parseDouble(precio);
            String postre = cboxpostre.getSelectedItem().toString();
            menuadmin2.agregarProductos("Postre",postre, preciodb);            
            tpreciopostre.setText("");
            JOptionPane.showMessageDialog(null, "Postre agregado");
        }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores de dinero en el campo de precio, no letras.");
        }
    }//GEN-LAST:event_bnewpostreActionPerformed

    private void cboxpostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxpostreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxpostreActionPerformed

    private void jButtonVerOrdenesHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerOrdenesHoraActionPerformed
        // TODO add your handling code here:
        List<Ordenes> horas= new ArrayList<>();
        horas=registroadmin2.getOrdenes();
        horas.sort(Comparator.comparing(Ordenes::getHora));
        
        // TODO add your handling code here:
        ordenesFrame ordenes = new ordenesFrame();
        ordenes.setTitle("Ordenes por hora");
        ordenesFrame.jTextArea1.append("Las ordenes son: ");
        int i = -1;
        Ordenes orden =null;
        for(int e = 0; e<horas.size();e++){
            orden = horas.get(e);
            i = i+1;
            //String comida = orden.getComida().getNombreComida();double precioc = orden.getComida().getPrecio();
            //String bebida = orden.getBebida().getNombreBebida();double preciob = orden.getBebida().getPrecio();
            String user = orden.getUsuario().getNombre();
            String carnet = orden.getUsuario().getCarnet();
            String hora = orden.getHora();
            String minuto = orden.getMinutos();
            //double sumaprecios = precioc + preciob;
            ordenesFrame.jTextArea1.append(System.getProperty("line.separator"));
            ordenesFrame.jTextArea1.append(i+".Usuario: "+user+" Carnet: "+carnet+", pidio el menu siguiente , para la siguiente hora: "+hora+":"+minuto+" :");
            Producto prod = new Producto();
            for(int k=0;k<orden.getPedido().size();k++){
                prod = orden.getPedido().get(k);
                ordenesFrame.jTextArea1.append(System.getProperty("line.separator"));
                ordenesFrame.jTextArea1.append(" - "+prod.getNombreProducto()+", con precio:"+prod.getPrecio());
            }
        }
        ordenes.setVisible(true);
        
    }//GEN-LAST:event_jButtonVerOrdenesHoraActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbuscarordenes;
    private javax.swing.JButton bentregarordenCola;
    private javax.swing.JButton bnewbebida;
    private javax.swing.JButton bnewcomida;
    private javax.swing.JButton bnewpostre;
    private javax.swing.JButton bordenespendientes;
    private javax.swing.JButton botonregresar;
    private javax.swing.JComboBox<String> cboxbebida;
    public static javax.swing.JComboBox<String> cboxcarnetsclientes;
    private javax.swing.JComboBox<String> cboxcomida;
    private javax.swing.JComboBox<String> cboxpostre;
    private javax.swing.JButton jButtonEntregarOrdenCarnetIndividual;
    private javax.swing.JButton jButtonVerOrdenesHora;
    public static javax.swing.JComboBox<String> jComboBoxBuscarOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tpreciobebida;
    private javax.swing.JTextField tpreciocomida;
    private javax.swing.JTextField tpreciopostre;
    // End of variables declaration//GEN-END:variables
}


