
package COMIDA_RED;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author SDiego
 */
public final class entFrame extends javax.swing.JFrame {
    public static Registro registroent; //La variable se declara "publica" y "de clase" para poder ser compartida
    public static Menus menuent;        //entre los diferentes JFrames creados.
    public static JComboBox<String> comboboxentc;
    public static JComboBox<String> comboboxentb;
    /**
     * Creates new form entFrame
     */
    public entFrame() {
        initComponents();
        this.setLocationRelativeTo(null); //El frame de entrada se localiza justamente en el centro de la pantalla. 
        
        registroent = new Registro();
        menuent = new Menus();
        comboboxentc = new JComboBox<>();
        comboboxentb = new JComboBox<>();
                
        menusIniciales();
        
    }
    /**
     * Metodo que inicializa cuatro comidas en el menu del restaurante.
     */
    public void menusIniciales(){
        menuent.agregarComidas("Porcion mediana de pizza", 12.00);
        menuent.agregarComidas("Quesoburguesa", 11.00);
        menuent.agregarComidas("Pie de queso", 8.00);
        menuent.agregarComidas("Papas con queso y tocino", 15.00);
        
        menuent.agregarBebidas("Seven Up", 6.00);
        menuent.agregarBebidas("Rosa de jamaica", 8.00);
        menuent.agregarBebidas("Horchata con canela", 8.00);
        menuent.agregarBebidas("Coca Cola", 6.00);
        
        
        
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbotonuser = new javax.swing.JRadioButton();
        rbotonadmin = new javax.swing.JRadioButton();
        botoningreso = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante RED, Pedidos Digitales");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido!!");

        jLabel2.setText("Elija una opcion porfavor:");

        buttonGroup1.add(rbotonuser);
        rbotonuser.setText("Ingresar como Usuario");
        rbotonuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbotonuserActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbotonadmin);
        rbotonadmin.setText("Ingresar como Administrador");

        botoningreso.setText("Ingresar");
        botoningreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoningresoActionPerformed(evt);
            }
        });

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbotonadmin)
                    .addComponent(rbotonuser))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botoningreso)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbotonuser)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(rbotonadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoningreso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbotonuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbotonuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbotonuserActionPerformed

    private void botoningresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoningresoActionPerformed
        // TODO add your handling code here:
        if (rbotonuser.isSelected()||rbotonadmin.isSelected()){
            if(rbotonuser.isSelected()){
                userFrame user = new userFrame(); //Se crea un objeto tipo userFrame "frame del usuario" 
                user.setVisible(true);            //y se vuelve visible.
                this.setVisible(false);           //Se oculta el frame en el que estamos actualmente.
                userFrame.registrouser = registroent; //Los objetos tipo Registro y Menus del frame del usuario se igualan 
                userFrame.menuuser = menuent;         //a los objetos respectivos de este Frame para que no se pierdan 
             //los datos al momento de pasar al otro frame. 
                userFrame.comboboxuserc = comboboxentc;
                userFrame.comboboxuserb = comboboxentb;
            }else if(rbotonadmin.isSelected()){
                adminFrame admin = new adminFrame();
                admin.setVisible(true);
                this.setVisible(false);               
                adminFrame.registroadmin = registroent;
                adminFrame.menuadmin = menuent;
                adminFrame.comboboxadminc = comboboxentc;
                adminFrame.comboboxadminb = comboboxentb;
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe de eligir al menos una opcion!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botoningresoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new entFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoningreso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbotonadmin;
    private javax.swing.JRadioButton rbotonuser;
    // End of variables declaration//GEN-END:variables
}
